#!/usr/bin/env bash

set -euo pipefail

WALLPAPER="$1"

properties="$(
    xfconf-query \
        -c xfce4-desktop \
        -p /backdrop \
        -l |
        grep -E 'screen.*/monitor.*/(image-path|last-image)$'
)"

while IFS= read -r property; do
    xfconf-query \
        -c xfce4-desktop \
        -p "$property" \
        -s "$WALLPAPER"
done <<<"$properties"
