#!/bin/bash

wallpaper="$(realpath "$1")"

if [[ ! -f "$wallpaper" ]]; then
    exit 1
fi

xfconf-query \
    -c xfce4-desktop \
    -p /backdrop/screen0/monitor0/image-path \
    -n -t string \
    -s "$wallpaper"

xfconf-query \
    -c xfce4-desktop \
    -p /backdrop/screen0/monitorVirtual-1/workspace0/last-image \
    -n -t string \
    -s "$wallpaper"
