#################
### AUTOSTART ###
#################

# Desktop services
exec mako
exec autotiling

# Battery notification
exec ~/.config/sway/scripts/battery-notify.sh

# Authentication / clipboard
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store
